shell = "zsh"


[templates]
source = "{{ hooks?.pre | nl }}{% for file in files %}source-with-zcompile \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source-with-zcompile \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"


# ---
# Load local configs
# ---
[plugins.local-configs]
local = "~/.config/zsh/config.d/"


# ---
# Install plugins
# ---
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-abbr]
github = "olets/zsh-abbr"
apply = ["defer"]

[plugins.enhancd]
github = "b4b4r07/enhancd"
apply = ["defer"]

[plugins.compinit]
inline = "zsh-defer -c \"autoload -Uz compinit && compinit\""


# ---
# Init CLI tools already installed
# ---
[plugins.mise]
inline = """
zsh-defer eval-script-with-cache \
  "mise activate zsh" \
  "$(which mise)"
"""

[plugins.starship]
inline = """
eval-script-with-cache \
  "starship init zsh" \
  "$(which starship)"
"""
