shell = "zsh"
apply = ["defer"]


[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"


[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.local-configs]
local = "~/.config/zsh/config.d/"
use = ["*.zsh"]
apply = ["source"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["source"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["source"]

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"
apply = ["source"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["source"]

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"

[plugins.starship]
inline = "eval \"$(starship init zsh)\""
