shell = "zsh"


[templates]
source = "{{ hooks?.pre | nl }}{% for file in files %}source_with_compile \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source_with_compile \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"


[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.local-configs]
local = "~/.config/zsh/config.d/"
use = ["*.zsh"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"

[plugins.zsh-abbr]
github = "olets/zsh-abbr"
apply = ["defer"]

[plugins.starship]
inline = "eval \"$(starship init zsh)\""
