shell = "zsh"
apply = ["defer"]


[templates]
source = """
{{ hooks?.pre | nl }}\
{% for file in files %}\
  source-with-zcompile \"{{ file }}\"\n\
{% endfor %}\
{{ hooks?.post | nl }}\
"""
defer = """
{{ hooks?.pre | nl }}\
{% for file in files %}\
  zsh-defer source-with-zcompile \"{{ file }}\"\n\
{% endfor %}\
{{ hooks?.post | nl }}\
"""


# ---
# Load local configs
# ---
[plugins.local-configs]
local = "~/.config/zsh/config.d/"
apply = ["source"]


# ---
# Install plugins
# ---
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"
hooks.post = """
zsh-defer -c '
  bindkey "\\t" menu-select  # Tab: Entering completion menu
  bindkey -M menuselect \\   # In completion menu
    "\\t" menu-complete \\   # Tab: Go to next item
    "$terminfo[kcbt]" reverse-menu-complete \\  # Shift + Tab: Go to previous item
    "^[[C" .accept-line \\   # Right: Select item
    "^[[D" .accept-line      # Left: Select item
  zstyle ":autocomplete:*" add-space  # Do not add space to selected item
'
"""

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

[plugins.enhancd]
github = "b4b4r07/enhancd"

[plugins.compinit]
inline = "zsh-defer -c \"autoload -Uz compinit && compinit\""


# ---
# Init CLI tools already installed
# ---
[plugins.mise]
inline = """
zsh-defer eval-script-with-cache \
  "mise activate zsh" \
  "$(which mise)"
"""

[plugins.starship]
inline = """
eval-script-with-cache \
  "starship init zsh" \
  "$(which starship)"
"""
