shell = "zsh"
apply = ["defer"]


[templates]
source = "{{ hooks?.pre | nl }}source-with-zcompile{% for file in files %} \\\n  {{ file }}{% endfor %}\n{{ hooks?.post | nl }}"
defer = "{{ hooks?.pre | nl }}zsh-defer source-with-zcompile{% for file in files %} \\\n  {{ file }}{% endfor %}\n{{ hooks?.post | nl }}"


[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]


# ---
# Install plugins
# ---
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"
hooks.post = """
zsh-defer -c '
  bindkey "\\t" menu-select  # Tab: Entering completion menu
  keybinds_in_completion_menu=(
    "\\t" menu-complete      # Tab: Go to next item
    "$terminfo[kcbt]" reverse-menu-complete # Shift + Tab: Go to previous item
    "^[[C" .accept-line      # Right: Select item   
    "^[[D" .accept-line      # Left: Select item
  )
  bindkey -M menuselect "$keybinds_in_completion_menu[@]"
  zstyle ":autocomplete:*" add-space  # Do not add space to selected item
'
"""

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

[plugins.enhancd]
github = "b4b4r07/enhancd"


# ---
# Init CLI tools already installed
# ---
[plugins.mise]
inline = """
zsh-defer eval-script-with-cache \
  "mise activate zsh" \
  "$(which -p mise)"
"""

[plugins.docker]
inline = """
zsh-defer eval-script-with-cache \
  "docker completion zsh" \
  "$(which docker)"
"""

[plugins.starship]
inline = """
eval-script-with-cache \
  "starship init zsh" \
  "$(which starship)"
"""


# ---
# Load local configs
# ---
[plugins.local-configs]
local = "~/.config/zsh/config.d/"
use = ["sync.zsh"]
apply = ["source"]

[plugins.local-configs-async]
local = "~/.config/zsh/config.d/"
use = ["async.zsh"]
