CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}
CACHE_HOME=${XDG_CACHE_HOME:-~/.cache}
DATA_HOME=${XDG_DATA_HOME:-~/.local/share}
STATE_HOME=${XDG_STATE_HOME:-~/.local/state}
# ignore: RUNTIME_DIR, DATA_DIRS, CONFIG_DIRS
