live_config_reload = true

[shell]
program = "zsh"
args = ["-l", "-c", "tmux a -t TERM || tmux new -s TERM"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 0 }
decorations_theme_variant = "Dark"

[font]
normal = { family = "HackGen35 Console NF", style = "Regular" }
size = 10.5
